######################################################

######################################################
# Washer timer automation
#######################################################
- alias: Washer Completes Wash
  trigger:
    - platform: state
      entity_id: sensor.washer_status
      to: 'running'
      for:
        minutes: 36
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.kodi_blue_iris
        message: 'Washer is Finished'
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: 'clean'




################### Porch lights on at night  ###########################
- alias: Porch Lights on
  trigger:
    - platform: sun
      event: sunset
#      offset: "00:30:00"
  action:
    - service: light.turn_on
      entity_id: light.carport
- alias: Porch Lights off
  trigger:
    - platform: sun
      event: sunrise
#      offset: "-00:30:00"
  action:
    - service: light.turn_off
      entity_id: light.carport


############ auto renew ssl   with notification if fails ####################
- alias: Auto Renew SSL Cert
  trigger:
    - platform: numeric_state
      entity_id: sensor.ssl_expire
      below: 29
  action:
    - service: shell_command.renew_ssl
########## Evening Time ##############
- alias: Evening Time
  trigger:
    - platform: time
      after: '19:01'
  condition:
    - condition: state
      entity_id: sensor.set_hold_mode
      state: 'home'
  action: 
   - service: light.turn_on
     data:
       entity_id: light.lamps
       color_temp: 426
       brightness: 125
  
    