######### cameras ###############
- platform: generic
  still_image_url: !secret radar 
  name: Radar
- platform: generic
  still_image_url: 'http://images.intellicast.com/WxImages/RadarLoop/msy_None_anim.gif'
  name: Radar Animated 
- platform: generic
  still_image_url: http://192.168.1.194/jpg/image.jpg
  name: Living_Room_Camera
  username: !secret iqeye_username
  password: !secret iqeye_password
- platform: foscam
  ip: 192.168.1.35
  port: 80
  username: !secret foscam_username
  password: !secret foscam_password
  name: Number 12 
- platform: foscam
  ip: 192.168.1.25
  port: 80
  username: !secret foscam_username
  password: !secret foscam_password
  name: Driveway  
- platform: foscam
  ip: 192.168.1.45
  port: 45
  username: !secret foscam_username
  password: !secret foscam_password
  name: Swamp
- platform: generic
  still_image_url: http://192.168.1.90/cgi-bin/camera
  name: Yard
- platform: generic
  still_image_url: http://192.168.1.75/now.jpg
  name: Back Door
  username: !secret iqeye_username
  password: !secret iqeye_password

  
- platform: generic
  name: Dawn
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.dawn_baby.attributes.latitude }},{{ states.device_tracker.dawn_baby.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.dawn_baby.attributes.latitude }},{{ states.device_tracker.dawn_baby.attributes.longitude }}
  limit_refetch_to_url_change: true  
  
- platform: generic
  name: Herb
  still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.herb_herb.attributes.latitude }},{{ states.device_tracker.herb_herb.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.herb_herb.attributes.latitude }},{{ states.device_tracker.herb_herb.attributes.longitude }}
  limit_refetch_to_url_change: true  
  
  
  
  
  
  