homeassistant:
  # Name of the location where Home Assistant is running
  name: Vas & Squrriels Castle
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 1
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  customize: !include Customize.yaml
  packages: !include_dir_named packages

####Zone files
zone: !include zones.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
   api_password: !secret http_password
   ssl_certificate: !secret http_ssl_cert
   ssl_key: !secret http_ssl_key
   base_url: !secret http_base_url
   use_x_forwarded_for: True
   trusted_networks:
     - 127.0.0.1
     - 192.168.1.0/24
   ip_ban_enabled: True
   login_attempts_threshold: 5
# Checks for available updates
updater:

recorder:
  exclude:
    domains:
      - input_select
      - media_player
      - automation
      - input_slider
      - rest_command
      - camera
      - notify
      - scene
      - light
      - sun
      - tts
      - device_tracker
      - mqtt
      - script
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_nearest_storm_distance
      - sensor.pws_observation_time
      - sensor.pws_alerts
      - sensor.pws_weather
      - sensor.pws_Temp_f
      - sensor.pws_feelslike_f
      - sensor.pws_wind_dir
      - sensor.pws_wind_mph
      - sensor.pws_wind_gust_mph
      - sensor.pws_relative_humidity
      - sensor.pws_precip_1hr_in
      - sensor.pws_precip_today_in
      - sensor.pws_visibility_mi
      - camera.radar
      - sun.sun
  db_url: !secret recorder_db_url
  purge_days: 10


# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - input_select
      - media_player
      - automation
      - input_slider
      - rest_command
      - camera
      - notify
      - scene
      - light
      - sun
      - tts
      - device_tracker
      - mqtt
      - script
    entities:
      - sensor.dark_sky_summary
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_minutely_summary
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_nearest_storm_distance
      - sensor.pws_observation_time
      - sensor.pws_alerts
      - sensor.pws_weather
      - sensor.pws_wind_dir
      - sensor.pws_wind_mph
      - sensor.pws_wind_gust_mph
      - sensor.pws_relative_humidity
      - sensor.pws_visibility_mi
      - camera.radar
      - sun.sun
# View all events in a logbook
logbook:
 exclude:
   domains:
      - input_select
      - media_player
      - automation
      - input_slider
      - rest_command
      - camera
      - notify
      - scene
logger:
  default: debug
  logs:
    homeassistant.components.zha: debug
    homeassistant.components.camera: critical
    homeassistant.components.sun: critical
    homeassistant.components.remote: critical
    homeassistant.components.switch: debug
    homeassistant.components.sensor: critical
    homeassistant.components.script: critical
    homeassistant.components.tts: critical
    homeassistant.components.media_player: critical
    homeassistant.components.input_select: critical
    homeassistant.components.input_slider: critical
    homeassistant.components.http: critical
    homeassistant.components.shell_command: critical
    homeassistant.components.device_tracker: critical
    homeassistant.components.mqtt: critical
    homeassistant.components.automation: critical
    homeassistant.components.websocket: critical
    homeassistant.components.discovery: critical
    homeassistant.components.light: critical
    homeassistant.components.ecobee: critical
    bellows.uart: debug
    homeassistant.core: critical
    homeassistant.helpers.script: warn
    homeassistant.helpers.entity: warn
    homeassistant.helpers.restore_state: warn
    homeassistant.loader: warn
    phue: warn
    plexapi: warn
    roku: critical
    dlipower.dlipower: warn
    myusps: warn


# Track the sun
sun:

browser:
  url: !secret browser

# Sensors
binary_sensor: !include binary_sensors.yaml
sensor: !include Sensors.yaml

# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

input_select: !include inputselect.yaml


media_player: !include players.yaml


remote:
  - platform: harmony
    name: Entertainment
    host: 192.168.1.193

group: !include tabs.yaml
camera: !include cameras.yaml
switch: !include switches.yaml

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1-255
  - platform: owntracks

mqtt:
  broker: m10.cloudmqtt.com
  port: 13636
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

alexa: !include alexaintents.yaml

script: !include scripts.yaml

automation old: !include automations old.yaml

light:
  platform: hue
  host: 192.168.1.185
  allow_unreachable: True

scene: !include Scenes.yaml

ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: True

notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

rest_command: !include restcommands.yaml

config:

shell_command:
  pihole_on: !secret pi_hole_on
  pihole_off: !secret pi_hole_off
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01
  update_hass: hassctl update-hass && hassctl config && hassctl restart
  update_git: gitupdate.sh
#zha:
#  usb_path: /dev/zigbee
#  database_path: /home/homeassistant/.homeassistant/zigbee.db
#zigbee:
#  device: /dev/ttyUSB1

#zwave:
#  usb_path: /dev/ttyUSB0

wink:
  access_token: !secret wink_access_token
#  refresh_token: Y68ELx0nrLagi_NphUl8vD4HYhcmRoEg
