homeassistant:
  # Name of the location where Home Assistant is running
  name: Vas & Squrriels Fish Tank
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: imperial
  time_zone: America/Chicago
  packages: !include_dir_named packages

frontend:

http:
   api_password: !secret http_password
   ssl_certificate: !secret http_ssl_cert
   ssl_key: !secret ssl_key
   base_url: !secret http_base_url
   use_x_forwarded_for: True
   trusted_networks:
     - 127.0.0.1
     - 192.168.1.0/24
   ip_ban_enabled: True
   login_attempts_threshold: 5

sun:

browser:
  url: !secret browser

group: !include tabs.yaml

mqtt:
  broker: 192.168.1.153
  port: 1883
  client_id: home-assistant-2
  keepalive: 60
  username: !secret mqtt_username_main
  password: !secret mqtt_password_main

config:

mqtt_statestream:
  base_topic: small_tank
  publish_attributes: false
  publish_timestamps: false
  include:
    domains:
      - sensor
      - binary_sensor
      - switch

sensor:
  - platform: serial
    serial_port: /dev/ttyACM0
    name: Arduino
    baudrate: 115200
#    scan_interval: 10
