homeassistant:
  # Name of the location where Home Assistant is running
  name: Vas & Squrriels Castle
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 1
  unit_system: imperial
  time_zone: America/Chicago
  packages: !include_dir_named packages
  
frontend:

http:
   api_password: !secret http_password
   ssl_certificate: !secret http_ssl_cert
   ssl_key: !secret ssl_key
   base_url: !secret http_base_url
   use_x_forwarded_for: True
   trusted_networks:
     - 127.0.0.1
     - 192.168.1.0/24
   ip_ban_enabled: True
   login_attempts_threshold: 5

updater:

conversation:

sun:

browser:
  url: !secret browser


group: !include tabs.yaml

mqtt:
  broker: 192.168.1.101
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

config:
