- platform: kodi
  host: 192.168.1.60
  port: 8888
  username: !secret media_player_kodi_username 
  password: !secret media_player_kodi_password 
- platform: samsungtv
  host: 192.168.1.18
  port: 8001
  name: Smart Tv
- platform: plex
  include_non_clients: false
- platform: onkyo
  host: 192.168.1.131
  name: Onkyo
  sources:
    dvd: 'Blue Iris'
    game: 'PS4'
    pc: 'Kodi'
    cd: 'PI'
    tv-cd: 'TV'
    tuner: 'Radio'
    net: 'Net'
- platform: roku
  host: 192.168.1.228
#- platform: roku
#  host: 192.168.1.80  
- platform: kodi
  host: 192.168.1.80
  name: Kodi Blue Iris
  port: 8080
  username: !secret media_player_kodi1_username 
  password: !secret media_player_kodi1_password 
  
