



      
######## Harmony remote  ######

- platform: template
  sensors:
    remote_entertainment:
      value_template: '{{ states.remote.entertainment.attributes.current_activity }}'
      friendly_name: 'Living Room'

###### VERSIONS
- platform: command_line
  command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
  name: Current Version

- platform: command_line
  name: Installed Version
  command: /srv/homeassistant/bin/hass --version

###### CUSTOM HA/Version
- platform: template
  sensors:
    ha_version:
      value_template: >-
        {% if is_state('sensor.current_version', states('sensor.installed_version')) %}
          {{ states('sensor.installed_version') }}
        {% else %}
          {{ states('sensor.current_version') }} Available
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.current_version', states('sensor.installed_version')) %}
          mdi:checkbox-marked
        {% else %}
          mdi:checkbox-blank-outline
        {% endif %}

- platform: template
  sensors:
    washer_status:
      friendly_name: 'Washing Machine Status'
      value_template: "{{ states('input_select.washing_machine_status') }}"
          
########################################################################
### cert expire check lets encrpt
########################################################################
- platform: cert_expiry
  host: !secret host_cert_expiry
  port: !secret port_expiry
  name: SSL Expire
  scan_interval: 120
########################################################################
#### dynamic battery levels
########################################################################
- platform: template
  sensors:
    kitchen_battery_motion:
      unit_of_measurement: '%'
      entity_id: sensor.motion_sensor_kitchen_battery
      value_template: >
          {% if states('sensor.motion_sensor_kitchen_battery') != "unknown" %}
            {{ states('sensor.motion_sensor_kitchen_battery')| int }}
          {% else %}
            0
          {% endif %}
      icon_template: >-
          {% if states('sensor.kitchen_battery_motion') != "unknown" %}
            {% set battery_level = states('sensor.kitchen_battery_motion')|int (-1)%}
            {% if battery_level == -1 %}
              mdi:battery-unknown
            {% else %}
              {% set battery_round = (battery_level|int / 10)|int * 10 %}
              {% if battery_round >= 100 %}
                mdi:battery
              {% elif battery_round > 0 %}
                mdi:battery-{{ battery_round }}
              {% else %}
                mdi:battery-alert
              {% endif %}
            {% endif %}
          {% else %}
            mdi:battery-alert
          {% endif %}


        