

############### USPS Sensor   ###############################
- platform: usps
  username: !secret usps_username
  password: !secret usps_password
- platform: ups
  username: !secret ups_username
  password: !secret ups_password
- platform: fedex
  username: !secret fedex_username
  password: !secret fedex_password
- platform: template
  sensors:
    packages_in_transit:
      friendly_name: "Packages in Transit"
      value_template: >
          {% macro in_transit(sensor) %}
            {{sensor.state|int - delivered(sensor)|int}}
          {% endmacro %}
          {% macro delivered(sensor) %}
            {% if 'delivered' in sensor.attributes %}
              {{sensor.attributes.delivered}}
            {% else %}
               0
            {% endif %}
          {% endmacro %}
          {{in_transit(states.sensor.usps_packages)|int + in_transit(states.sensor.ups)|int  + in_transit(states.sensor.fedex)|int}}
    deliveries_today:
      friendly_name: "Today's Deliveries"
      value_template: >
          {% macro delivered(sensor) %}
            {% if 'delivered' in sensor.attributes %}
              {{sensor.attributes.delivered}}
            {% else %}
               0
            {% endif %}
          {% endmacro %}
          {{delivered(states.sensor.usps_packages)|int + delivered(states.sensor.ups)|int + delivered(states.sensor.fedex)|int}}
############################################################
############## Public Ip
- platform: dnsip

######## Equipment ########
- platform: speedtest
  minute:
    - 0
    - 59
  monitored_conditions:
    - ping
    - download
    - upload
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
      
######## Harmony remote  ######

- platform: template
  sensors:
    remote_entertainment:
      value_template: '{{ states.remote.entertainment.attributes.current_activity }}'
      friendly_name: 'Living Room'

###### VERSIONS
- platform: command_line
  command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
  name: Current Version

- platform: command_line
  name: Installed Version
  command: /srv/homeassistant/bin/hass --version

###### CUSTOM HA/Version
- platform: template
  sensors:
    ha_version:
      value_template: >-
        {% if is_state('sensor.current_version', states('sensor.installed_version')) %}
          {{ states('sensor.installed_version') }}
        {% else %}
          {{ states('sensor.current_version') }} Available
        {% endif %}
      icon_template: >-
        {% if is_state('sensor.current_version', states('sensor.installed_version')) %}
          mdi:checkbox-marked
        {% else %}
          mdi:checkbox-blank-outline
        {% endif %}

- platform: template
  sensors:
    washer_status:
      friendly_name: 'Washing Machine Status'
      value_template: "{{ states('input_select.washing_machine_status') }}"
          
########################################################################
### cert expire check lets encrpt
########################################################################
- platform: cert_expiry
  host: !secret host_cert_expiry
  port: !secret port_expiry
  name: SSL Expire
  scan_interval: 120
########################################################################
#### dynamic battery levels
########################################################################
- platform: template
  sensors:
    kitchen_battery_motion:
      unit_of_measurement: '%'
      entity_id: sensor.motion_sensor_kitchen_battery
      value_template: >
          {% if states('sensor.motion_sensor_kitchen_battery') != "unknown" %}
            {{ states('sensor.motion_sensor_kitchen_battery')| int }}
          {% else %}
            0
          {% endif %}
      icon_template: >-
          {% if states('sensor.kitchen_battery_motion') != "unknown" %}
            {% set battery_level = states('sensor.kitchen_battery_motion')|int (-1)%}
            {% if battery_level == -1 %}
              mdi:battery-unknown
            {% else %}
              {% set battery_round = (battery_level|int / 10)|int * 10 %}
              {% if battery_round >= 100 %}
                mdi:battery
              {% elif battery_round > 0 %}
                mdi:battery-{{ battery_round }}
              {% else %}
                mdi:battery-alert
              {% endif %}
            {% endif %}
          {% else %}
            mdi:battery-alert
          {% endif %}

