- platform: digitalloggers
  host: 192.168.1.40
  password: !secret digital_loggers_pass
  name: Network Switch
  cycletime: 5
  
  
######################### PI Hole #########################
- platform: template
  switches:
    pihole:
      value_template: "{{ is_state('binary_sensor.pihole_status', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.pihole_on
      turn_off:
        service: script.turn_on
        entity_id: script.pihole_off  