homeassistant:
  customize:
    binary_sensor.motion_outdoor_shed:
      friendly_name: Shed Camera
      device_class: motion
    binary_sensor.motion_outdoor_driveway:
      friendly_name: Driveway
      device_class: motion
    binary_sensor.motion_outdoor_frontdoor:
      friendly_name: Front Door
      device_class: motion
    binary_sensor.motion_outdoor_number12:
      friendly_name: Number 12
      device_class: motion
    binary_sensor.motion_outdoor_backdoor:
      friendly_name: Back Door
      device_class: motion
    binary_sensor.motion_outdoor_swamp:
      friendly_name: Swamp
      device_class: motion

#######################################################################################################################
###### Sets profile on blue iris   ####################################################################################
#######################################################################################################################      
sensor:
  - platform: rest
    resource: !secret rest_blue_iris_profile
    value_template: >-
       {% if 'profile=1' in value %}
         No Motion Detection
       {% elif 'profile=5' in value %}
         Lockdown Full Motion Detection
       {% elif 'profile=6' in value %}
         Sleep
       {% endif %}
    name: 'Blue Iris Profile'      
    
#######################################################################################################################
###### Motion sensor templates for blue Iris  #########################################################################
#######################################################################################################################  
binary_sensor:
  - platform: template
    sensors:
      motion_outdoor_shed:
#        friendly_name: 'Shed Cam'
        value_template: >-
          {% if states('binary_sensor.blueirisshed') %}
          {% if is_state('binary_sensor.blueirisshed', 'on') %}
             True
          {% elif is_state('binary_sensor.blueirisshed', 'off') %}
             False
          {% else %}
          {{ states('binary_sensor.blueirisshed') }}
          {% endif %}
          {% else %}
            False
          {% endif %}
  - platform: template
    sensors:
      motion_outdoor_driveway:
#        friendly_name: 'Driveway'
        value_template: >-
           {% if states('binary_sensor.blueiriscam2') %}
           {% if is_state('binary_sensor.blueiriscam2', 'on') %}
              True
           {% elif is_state('binary_sensor.blueiriscam2', 'off') %}
              False
           {% else %}
           {{ states('binary_sensor.blueiriscam2') }}
           {% endif %}
           {% else %}
             False
           {% endif %}
  - platform: template
    sensors:
      motion_outdoor_number12:
#        friendly_name: 'Number 12'
        value_template: >-
          {% if states('binary_sensor.blueiriscam6') %}
          {% if is_state('binary_sensor.blueiriscam6', 'on') %}
             True
          {% elif is_state('binary_sensor.blueiriscam6', 'off') %}
             False
          {% else %}
          {{ states('binary_sensor.blueiriscam6') }}
          {% endif %}
          {% else %}
            False
          {% endif %}
  - platform: template
    sensors:
      motion_outdoor_swamp:
 #       friendly_name: 'Swamp'
        value_template: >-
          {% if states('binary_sensor.blueiriscam5') %}
          {% if is_state('binary_sensor.blueiriscam5', 'on') %}
             True
          {% elif is_state('binary_sensor.blueiriscam5', 'off') %}
             False
          {% else %}
          {{ states('binary_sensor.blueiriscam5') }}
          {% endif %}
          {% else %}
            False
          {% endif %}
  - platform: template
    sensors:
      motion_outdoor_frontdoor:
#        friendly_name: 'Front Door'
        value_template: >-
          {% if states('binary_sensor.blueiriscam4') %}
          {% if is_state('binary_sensor.blueiriscam4', 'on') %}
             True
          {% elif is_state('binary_sensor.blueiriscam4', 'off') %}
             False
          {% else %}
          {{ states('binary_sensor.blueiriscam4') }}
          {% endif %}
          {% else %}
            False
          {% endif %}
  - platform: template
    sensors:
      motion_outdoor_backdoor:
#        friendly_name: 'Back Door'
        value_template: >-
          {% if states('binary_sensor.blueiriscam3') %}
          {% if is_state('binary_sensor.blueiriscam3', 'on') %}
             True
          {% elif is_state('binary_sensor.blueiriscam3', 'off') %}
             False
          {% else %}
          {{ states('binary_sensor.blueiriscam3') }}
          {% endif %}
          {% else %}
            False
          {% endif %}        
      
automation:
  ######################################################
# Flash Door lamp when motion at shed camera
######################################################
  - alias: Flash Red on Motion
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_shed 
        to: 'True'
    condition: 
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'
      - condition: time
        after: '07:00:00'
        before: '19:00:00:00'  
    action:
      - service: light.turn_on
        data:
          entity_id: light.door_lamp    
          flash: short
          color_name: Red
  - alias: Back to White after Motion
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_shed 
        to: 'False'
    condition: 
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'
      - condition: time
        after: '07:00:00'
        before: '19:00:00'  
    action:
      - service: light.turn_on
        data:
          entity_id: light.door_lamp
          color_temp: 154
          brightness: 255        
      