########################################################################
### cert expire check lets encrpt
########################################################################
sensor:
  - platform: cert_expiry
    host: !secret host_cert_expiry
    port: !secret port_expiry
    name: SSL Expire
    scan_interval: 1200
  
shell_command:
  renew_ssl: ~/certbot/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01  
  
automation:
  - alias: Auto Renew SSL Cert
    trigger:
      - platform: numeric_state
        entity_id: sensor.ssl_expire
        below: 29
    action:
      - service: shell_command.renew_ssl  