homeassistant:
  customize:
    script.herbearly_on:
      friendly_name: Morning

#########################################################################################
#                                                                                   ##### 
#                   Early Morning Mode                                              #####
#                                                                                   #####  
#########################################################################################
script:
  herbearly_on:
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.network_switch_blue_iris_monitor
      - delay: '00:00:01' 
      - service: script.blinds_halfway
      - service: input_select.select_option
        data:
          entity_id: input_select.harmony
          option: 'Classic Music'
      - delay: '00:00:02'    
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.stereo
          volume_level: '.60'        
      - service: light.turn_on
        data:      
          entity_id: light.herbs_lamp
          color_temp: 200
          brightness: 175
      - delay: '00:00:03'    
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.kodi_blue_iris
          volume_level: '.30'    
      - service: tts.google_say
        data_template:
          entity_id: media_player.kodi_blue_iris
          message: 'Good Morning Herb how are you this morning The weather for today is{{states.sensor.dark_sky_daily_summary.state}}'
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.kodi_blue_iris
          volume_level: '1'    
      - service: rest_command.no_motion
      - service: rest_command.no_motion      
      
# rest_command sets profile of blue iris software      