homeassistant:
  customize:
    sensor.set_hold_mode:         
      icon: mdi:home
    sensor.hvac_fan:
      haaska_hidden: true   
      icon: mdi:fan   
  
##### Config for ecobee
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: True
  
group:
  room_occupancy_card:
   name: Occupancy
   entities:
     - binary_sensor.thermostat_occupancy   
     - binary_sensor.ruths_room_occupancy
     - binary_sensor.master_bedroom_occupancy
     - binary_sensor.living_room_occupancy  
  ecobee_sensors_card:
   name: Ecobee Temp Sensors
   entities:
     - sensor.master_bedroom_temperature   
     - sensor.living_room_temperature
     - sensor.ruths_room_temperature
     - sensor.thermostat_humidity
     - sensor.thermostat_temperature
  climate_temp_card:
   name: Climate
   entities:
     - climate.thermostat
     - sensor.operating_mode
     - sensor.hvac_fan
     - sensor.thermostat_humidity
     - sensor.thermostat_temperature
     - sensor.master_bedroom_temperature   
     - sensor.living_room_temperature
     - sensor.ruths_room_temperature
     - sensor.pws_Temp_f     


######  ecobee3 Mode Sensors  
sensor:
  - platform: template
    sensors:
      operating_mode:
        friendly_name: 'Current Operation'
        value_template: "{{ states.climate.thermostat.attributes.operation }}"
  - platform: template
    sensors:
      set_hold_mode:
        friendly_name: 'Current Mode'
        value_template: "{{ states.climate.thermostat.attributes.hold_mode }}"
  - platform: template
    sensors:
      target_temp:
        friendly_name: 'Target Temperature'
        value_template: "{{ states.climate.thermostat.attributes.target_temp_high }}"
  - platform: template
    sensors:
      current_temp:
        friendly_name: 'Current Temperature'
        value_template: "{{ states.climate.thermostat.attributes.current_temperature }}"      
  - platform: template
    sensors:
      hvac_fan:
        friendly_name: 'Hvac Fan'
        value_template: "{{ states.climate.thermostat.attributes.fan }}"  