################### Porch lights on at night  ###########################
homeassistant:
  customize:
    automation.porch_lights_on:
      friendly_name: "Porch Lights On"
      haaska_hidden: true
      hidden: false
      
    automation.porch_lights_off:
      friendly_name: "Porch Lights Off"
      haaska_hidden: true
      hidden: false   

    automation.carport_bright_and_white_on_motion:
      friendly_name: "Porch Lights White On Motion"
      haaska_hidden: true
      hidden: false 

    automation.back_to_yellow_dim_after_Motion:
      friendly_name: "Porch Lights yellow no Motion"
      haaska_hidden: true
      hidden: false   

group:
  carport_lights:
   control: hidden
   name: Carport
   entities:
     - light.carport
     - automation.porch_lights_on
     - automation.porch_lights_off
     - automation.carport_bright_and_white_on_motion
     - automation.back_to_yellow_dim_after_Motion
     
automation:
  - alias: Porch Lights on
    initial_state: 'on'
    trigger:
      - platform: sun
        event: sunset
#      offset: "00:30:00"
    action:
      - service: light.turn_on
        data:
          entity_id: light.carport
          color_temp: 426
          brightness: 125          
  - alias: Porch Lights off
    trigger:
      - platform: sun
        event: sunrise
#      offset: "-00:30:00"
    action:
      - service: light.turn_off
        entity_id: light.carport
        
# brigten porch light if motion from shed camera


  - alias: Carport bright and white on motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_shed 
        to: 'on'
    condition: 
      - condition: state
        entity_id: light.carport
        state: 'on'
    action:
      - service: light.turn_on
        data:
          entity_id: light.carport    
          color_temp: 154
          brightness: 255   
          
  - alias: Back to yellow dim after Motion
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_outdoor_shed 
        to: 'off'
    condition: 
      - condition: state
        entity_id: light.carport
        state: 'on'
    action:
      - delay: '00:00:30'
      - service: light.turn_on
        data:
          entity_id: light.carport
          color_temp: 426
          brightness: 125           