homeassistant:
  customize:
    sensor.glances_cpu_load:
      friendly_name: Cpu Load
      icon: mdi:desktop-tower 
    sensor.glances_disk_free:
      friendly_name: Hard Drive Free Space
      icon: mdi:harddisk
    sensor.glances_disk_use:
      friendly_name: Hard Drive Used
      icon: mdi:harddisk
    sensor.glances_disk_use_2:
      friendly_name: Hard Drive Use
      icon: mdi:harddisk
    sensor.glances_ram_free:
      friendly_name: Ram Free
      icon: mdi:chip
    sensor.glances_ram_use:
      friendly_name: Ram Used
      icon: mdi:chip
    sensor.glances_ram_use_2:
      friendly_name: Ram Used
      icon: mdi:chip       
            
group:
  network_workstation_info_card:
   name: Network Pc Svr Info
   entities:
     - sensor.network_workstation
     - sensor.glances_cpu_load
     - sensor.glances_disk_free
     - sensor.glances_disk_use_2
     - sensor.glances_disk_use
     - sensor.glances_ram_use_2
     - sensor.glances_ram_free
     - sensor.glances_ram_use
     
sensor:
  - platform: glances
    host: !secret glances_network_workstation
    port: !secret glances_network_workstation_port
    resources:
      - 'disk_use_percent'
      - 'disk_use'
      - 'disk_free'
      - 'memory_use_percent'
      - 'memory_use'
      - 'memory_free'
      - 'swap_use_percent'
      - 'swap_use'
      - 'swap_free'
      - 'processor_load'
      - 'process_running'
      - 'process_total'
      - 'process_thread'
      - 'process_sleeping'
     