homeassistant:
  customize:
    sensor.ha_version:   
      friendly_name: New Ha Release  
    script.update_home_assistant_home:
      friendly_name: Home Assistant Update
      icon: mdi:update       

sensor:
  ###### VERSIONS
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: Current Version

  - platform: command_line 
    name: Installed Version
    command: /srv/homeassistant/bin/hass --version

###### CUSTOM HA/Version
  - platform: template
    sensors:
      ha_version:
        value_template: >-
          {% if is_state('sensor.current_version', states('sensor.installed_version')) %}
            {{ states('sensor.installed_version') }}
          {% else %}
            {{ states('sensor.current_version') }} Available
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.current_version', states('sensor.installed_version')) %}
            mdi:checkbox-marked
          {% else %}
            mdi:checkbox-blank-outline
          {% endif %}  
script:
  update_home_assistant_home:
    sequence: 
      - service: shell_command.update_hass
shell_command:
  update_hass: hassctl update-hass && hassctl config && hassctl restart      
      