################################################################
## Package / HAASKA
################################################################

################################################
## Customize
################################################

homeassistant:
  customize_domain:
    alert:
      haaska_hidden: false

    automation:
      haaska_hidden: true

    climate:
      haaska_hidden: false

    cover:
      haaska_hidden: false

    fan:
      haaska_hidden: false

    group:
      haaska_hidden: true

    input_boolean:
      haaska_hidden: true

    input_slider:
      haaska_hidden: true

    light:
      haaska_hidden: false

    lock:
      haaska_hidden: false

    media_player:
      haaska_hidden: false

    scene:
      haaska_hidden: false

    script:
      haaska_hidden: false

    switch:
      haaska_hidden: false