automation:
  - alias: Ha Start
    initial_state: 'on'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - service: switch.turn_on
        entity_id: switch.relay_three
      # - service: switch.turn_on
      #   entity_id: switch.relay_four  
