homeassistant:
  customize:
  ################################################
  ## Binary Sensor
  ################################################
  
    binary_sensor.kitchen_motion:
      friendly_name: Kitchen Motion
      device_class: motion
    binary_sensor.hallway_motion:
      friendly_name: Hallway Motion
      device_class: motion 
    binary_sensor.laundry_room_motion:
      friendly_name: Laundry Room Motion
      device_class: motion       
    binary_sensor.kids_hallway_motion:
      friendly_name: Kids Hallway Motion
      device_class: motion
    binary_sensor.master_motion:
      friendly_name: Master Motion
      device_class: motion
  ################################################
  ##  Sensor Battery Icon
  ################################################    
    sensor.motion_sensor_kids_hall_battery:
      icon: mdi:battery     
    sensor.motion_sensor_laundry_battery:
      icon: mdi:battery    
    sensor.motion_sensor_hallway_battery:
      icon: mdi:battery
#     sensor.motion_sensor_kitchen_battery:
#        icon: mdi:battery
    sensor.kitchen_battery_motion:
      friendly_name: Kitchen Motion Battery
    sensor.motion_sensor_kids_bathroom_battery:
      icon: mdi:battery
    sensor.motion_sensor_master_battery:
      icon: mdi:battery
    
    
####### Binary sensor motion   #############  
binary_sensor:  
  - platform: rest
    resource: !secret MS_rest_6
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: kitchen_motion 
  - platform: rest
    resource: !secret MS_rest_12
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: hallway_motion    
  - platform: rest
    resource: !secret MS_rest_20
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: laundry_room_motion 
  - platform: rest
    resource: !secret MS_rest_24
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: kids_hallway_motion   
  - platform: rest
    resource: !secret MS_rest_30
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 2
    name: kids_bathroom_motion  
   
################# sensor temp ########################
sensor:
  - platform: rest
    resource: !secret MS_rest_39
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Master Temperature'    

  - platform: rest
    resource: !secret MS_rest_23
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Kids Hallway Temperature'    
  - platform: rest
    resource: !secret MS_rest_11
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Hallway Temperature'
  - platform: rest
    resource: !secret MS_rest_5
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Kitchen Temperature' 
  - platform: rest
    resource: !secret MS_rest_29
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Kids Bathroom Temperature'    

##################### sensor battery   ##############################
  - platform: rest
    resource: !secret MS_rest_5
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Kitchen Battery'
  - platform: rest
    resource: !secret MS_rest_11
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Hallway Battery'
  - platform: rest
    resource: !secret MS_rest_19
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'Laundry Temperature'
  - platform: rest
    resource: !secret MS_rest_20
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Laundry Battery'
  - platform: rest
    resource: !secret MS_rest_23
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Kids Hall Battery'
  - platform: rest
    resource: !secret MS_rest_30
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Kids Bathroom Battery'

  - platform: rest
    resource: !secret MS_rest_39
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Motion Sensor Master Battery'  
    

    
                  
         
                        
          
          