homeassistant:
  customize:
    input_boolean.boolean_sunrise:
      friendly_name: Sunrise
      hasska_hidden: true
    automation.sunrise:
      friendly_name: Sunrise
      hasska_hidden: true      
      
input_boolean:
  boolean_sunrise:
    initial: off
    
automation:
  - alias: "sunrise"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: sun
        event: sunrise
        offset: "-00:30:00"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_card
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_sunrise
      - service: shell_command.sunrise
      
shell_command:
  sunrise: 'echo -n "u" > /dev/ttyACM0 115200'      
    
    