homeassistant:
  customize:
    input_boolean.boolean_midday:
      friendly_name: MidDay
      hasska_hidden: true
    automation.midday:
      friendly_name: MidDay
      hasska_hidden: true

input_boolean:
  boolean_midday:
    initial: off

automation:
  - alias: "midday"
    initial_state: true
    hide_entity: false
    trigger:
      - platform: sun
        event: sunrise
        offset: "02:00:00"
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: group.input_boolean_card
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_midday
      - service: shell_command.midday

shell_command:
  midday: 'echo -n "d" > /dev/ttyACM0 115200'
