homeassistant:
  customize:

#     input_boolean.boolean_moon_fade:
#       friendly_name: Fade Moon Lights
#       hasska_hidden: true
#     input_boolean.boolean_moon_lights_off:
#       friendly_name: Moon Lights Off
#       hasska_hidden: true
# #      persistent: true
#     input_boolean.boolean_thunderstorm:
#       friendly_name: Thunderstorm
#       hasska_hidden: true
# #      persistent: true
#     input_boolean.boolean_rain:
#       friendly_name: Rain
#       hasska_hidden: true
# #      persistent: true
    sensor.small_tank_lights_mode:
      friendly_name: Small Tank Light Mode
      hasska_hidden: true
      icon: mdi:fish
    sensor.small_tank_lights_weather:
      friendly_name: Small Tank Lights Weather Effect
      hasska_hidden: true
      icon: mdi:fish
#
group:
  input_boolean_card:
    name: Input Boolean Tank Light Mode
    entities:
      - input_boolean.boolean_midnight_blue
      - input_boolean.boolean_sunrise
      - input_boolean.boolean_morning_evening
      - input_boolean.boolean_midday
      - input_boolean.boolean_moonlight
#       - input_boolean.boolean_afternoon
#       - input_boolean.boolean_evening
      - input_boolean.boolean_sunset
#       - input_boolean.boolean_moon_fade
      - input_boolean.boolean_leds_off
#       - input_boolean.boolean_thunderstorm
#       - input_boolean.boolean_rain
#       - sensor.small_tank_lights_mode
#       - sensor.small_tank_lights_weather
#
# input_boolean:

#   boolean_moon_fade:
#     initial: off
#   boolean_moon_lights_off:
#     initial: off
#   boolean_thunderstorm:
#     initial: off
#   boolean_rain:
#     initial: off
#
sensor:
  - platform: template
    sensors:
      light_mode:
        value_template: '{{states.sensor.arduino.attributes.Status}}'

  - platform: template
    sensors:
      small_tank_lights_mode:
        value_template: >-
          {% if states('input_boolean.boolean_midnight_blue') == 'on' %}
              Midnight Blue
          {% elif states('input_boolean.boolean_sunrise') == 'on' %}
              Sunrise
          {% elif states('input_boolean.boolean_morning_evening') == 'on' %}
              Midmorning/Midevening
          {% elif states('input_boolean.boolean_midday') == 'on' %}
              Midday Sunny
          {% elif states('input_boolean.boolean_sunset') == 'on' %}
              Sunset
          {% elif states('input_boolean.boolean_moonlight') == 'on' %}
              Moonlight
          {% elif states('input_boolean.boolean_leds_off') == 'on' %}
              Lights Off
          {% else %}
              None
          {% endif %}

  - platform: template
    sensors:
      small_tank_lights_weather:
        value_template: >-
           {% if states('input_boolean.boolean_thunderstorm') == 'on' %}
              Thunderstorm's
           {% elif states('input_boolean.boolean_rain') == 'on' %}
              Rain
           {% elif states('input_boolean.boolean_midday_cloudy') == 'on' %}
              Midday Cloudy
           {% else %}
              None
           {% endif %}
