

logger:
  default: error
  logs:
    homeassistant.components.sun: critical
    homeassistant.components.switch: critical
    homeassistant.components.sensor: critical
    homeassistant.components.script: critical
    homeassistant.components.http: critical
    homeassistant.components.shell_command: debug
    homeassistant.components.device_tracker: critical
    homeassistant.components.mqtt: critical
    homeassistant.components.automation: critical
    homeassistant.components.light: critical
    homeassistant.helpers.script: warn
    homeassistant.helpers.entity: warn
    homeassistant.helpers.restore_state: warn
    homeassistant.loader: warn

  ################### Logger level
input_select:
  log_level:
    name: Log Level
    options:
     - critical
     - fatal
     - error
     - warning
     - warn
     - info
     - debug
     - notset
    initial: warn


  ############################# Sets Logging Level
automation:
  - alias: Log Level
    trigger:
      - platform: state
        entity_id: input_select.log_level
    action:
      - service: logger.set_level
        data_template:
          homeassistant.components: "{{ trigger.to_state.state }}"
