homeassistant:
  customize:
    automation.motion_master_bedroom:
      haaska_hidden: true
      hidden: true
      persistence: true
      
sensor:
  - platform: rest
    resource: !secret MS_rest_40
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 1
    name: master_motion      
  
  
#######################################################################################################
#####    When home mode set on ecobee then master light turns on in bedroom (not while sleeping  ###### 
#####    ie house is in sleep mode                                                               ######
#####    use case app only allows set times and we go to bed at diff times                       ######
#######################################################################################################

automation:
  - alias: Motion Master Bedroom
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.master_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'  
    action:
      - service: light.turn_on
        data:
          entity_id: light.master
          color_temp: 154
          brightness: 255     