homeassistant:
  customize:
    binary_sensor.kids_bathroom_motion:
      friendly_name: Kids Bathroom Motion
      device_class: motion
    automation.master_bath_light_left_on:
      haaska_hidden: true
      hidden: true
      persistence: true
    automation.master_bath_shower_time_off:
      haaska_hidden: true
      hidden: true
      persistence: true
    automation.master_bath_shower_time_on:
      haaska_hidden: true
      hidden: true
      persistence: true      
    automation.motion_bathroom_home_mode_off:
      haaska_hidden: true
      hidden: true 
      persistence: true
    automation.motion_bathroom_home_mode_on:
      haaska_hidden: true
      hidden: true 
      persistence: true
    automation.motion_bathroom_sleep_off:
      haaska_hidden: true
      hidden: true 
      persistence: true
    automation.motion_bathroom_sleep_on:
      haaska_hidden: true
      hidden: true 
      persistence: true
   
sensor:
  - platform: rest
    resource: !secret MS_rest_36
    value_template: '{{ value_json.state.presence }}'
    scan_interval: 1 
    name: bathroom_motion    
  
automation:  
  - alias: Motion Bathroom Home Mode On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'   
    action:
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 154
          brightness: 255       
  - alias: Motion Bathroom Home Mode off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'off'
        for:
          minutes: 10 
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'  
    action:
      - service: light.turn_off
        entity_id: light.bathroom
              
  - alias: Motion Bathroom Sleep On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'on'
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'  
    action:
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 426
          brightness: 90    
  - alias: Motion Bathroom Sleep Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.bathroom_motion
        to: 'off'
        for:
          minutes: 5
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'sleep'
    action:
      - service: light.turn_off
        entity_id: light.bathroom
  - alias: Master Bath Shower Time On
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.master_bathroom_dimmer_state
        to: 'On'
    action:
      - service: automation.turn_off
        entity_id: automation.motion_bathroom_home_mode_off
      - service: automation.turn_off
        entity_id: automation.motion_bathroom_sleep_off  
      - service: light.turn_on
        data:
          entity_id: light.bathroom_vanity
          color_temp: 154
          brightness: 255  
      - service: light.turn_on
        data:
          entity_id: light.bathroom
          color_temp: 154
          brightness: 255
  - alias: Master Bath Shower Time Off
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.master_bathroom_dimmer_state
        to: 'Off'
    action:
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_home_mode_on
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_sleep_on
      - service: light.turn_off
        entity_id: light.bathroom_vanity
      - service: light.turn_off
        entity_id: light.bathroom
  - alias: Master Bath light left on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: light.bathroom_vanity
        to: 'On'
        for:
          hours: 1
    action:
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_home_mode_on
      - service: automation.turn_on
        entity_id: automation.motion_bathroom_sleep_on
      - service: light.turn_off
        entity_id: light.bathroom_vanity
      - service: light.turn_off
        entity_id: light.bathroom      