homeassistant:
  customize:
    switch.relay_three:
     icon: mdi:water-pump
     friendly_name: HOB Filter
     
    switch.relay_one:
      icon: mdi:led-strip
      friendly_name: White Lights
      
    switch.relay_two:
      icon: mdi:thermometer-lines
      friendly_name: Heater    
      
    switch.relay_four:
     icon: mdi:led-strip
     friendly_name: Fish Tank Led Controller
    
   
group:
  relay_card:
   control: hidden
   name: Fish Tank Controls
   entities:
     - switch.relay_one
     - switch.relay_two
     - switch.relay_three
     - switch.relay_four

switch:
  - platform: rpi_gpio
    ports:
      18: Relay Three
      25: Relay One
      23: Relay Two
      24: Relay Four 
    invert_logic: true  
