homeassistant:
  customize:
    sensor.dht_sensor_temperature:
      friendly_name: Hood Temperature
      icon: mdi:temperature-fahrenheit
      hasska_hidden: true
      unit_of_measurement: '°F'
    sensor.dht_sensor_humidity:
      friendly_name: Hood Humidity
      icon: mdi:water-percent
      hasska_hidden: true
      unit_of_measurement: '%'
    # sensor.water_temp:
    #   friendly_name: Water Temp
    #   icon: mdi:temperature-fahrenheit
    #   hasska_hidden: true
    # sensor.temp_reading:
    #   friendly_name: Water Temp Reading
    #   icon: mdi:temperature-fahrenheit
    #   hasska_hidden: true
    sensor.water_temperature:
      freindly_name: Water Temp Reading
      icon: mdi:temperature-fahrenheit
      hasska_hidden: true
      unit_of_measurement: '°F'

group:
  ha_temp_humd_card:
   name: Home Assistant Exterior Temps
   entities:
     - sensor.dht_sensor_temperature
     - sensor.dht_sensor_humidity
     - sensor.server_cpu_temperature
     - sensor.hood_temperature

  water_sensors:
   name: Small Tank Temp Sensors
   entities:
     - sensor.water_temperature
     - input_boolean.boolean_tank_temp_warning

sensor:
  - platform: template
    sensors:
      water_temperature:
        value_template: '{{states.sensor.arduino.attributes.water_temp | round(1)}}'
    scan_interval: 10
    
  - platform: dht
    sensor: DHT22
    pin: 4
    temperature_offset: -9.9
    humidity_offset: -3.2
    monitored_conditions:
      - temperature
      - humidity

  # - platform: arduino
  #   pins:
  #     2:
  #       name: Temp Probe

#### cmds to get second temp from pi
#### sudo modprobe w1-gpio
#### sudo dtoverlay w1-gpio gpiopin=17 pullup=0 # header pin 11
#### ls /sys/bus/w1/devices/

#### To enable the one-wire interface you need to add the following line to /boot/config.txt, before rebooting your Pi:
#### dtoverlay=w1-gpio
#### dtoverlay=w1-gpio,gpiopin=x
