homeassistant:
  customize:
    sensor.water_level:
      icon: mdi:gauge
      friendly_name: Water Level
    input_boolean.boolean_tank_water_level_warning:
      friendly_name: Water Level Warning
      
group:
  water_level_card:
    control: hidden
    name: Small Tank Water Level
    entities:
      - sensor.water_level
      - input_boolean.boolean_tank_water_level_warning

input_boolean:
  boolean_tank_water_level_warning:
    initial: off      

binary_sensor:
  - platform: rpi_gpio
    ports:
      21: Water Level
      
sensor:
  - platform: template
    sensors:
      water_level:
        value_template: '{% if is_state("binary_sensor.water_level", "off") %}Water Level Ok{% else %}Water Level Low{% endif %}'      
   
automation:
  #### This turns on boolean so that main ha will send a txt and push that there is a problem             
  - alias: Tank Water Level needs attention
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.water_level
        to: 'on'
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.boolean_tank_water_level_warning   
           
  - alias: Tank Temp ok
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.water_level
        to: 'off'
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.boolean_tank_water_level_warning       
          
          