homeassistant:
  customize:
    sensor.pws_alerts:
      icon: mdi:alert-outline 
      friendly_name: Alerts 
    sensor.pws_feelslike_f:
      friendly_name: Feels Like
    sensor.pws_temp_f:
      friendly_name: Temperature
    sensor.pws_observation_time:
      icon: mdi:timer-sand
      friendly_name: Observation Time 
    sensor.pws_weather:
      friendly_name: Conditions 
    sensor.pws_wind_dir:
      icon: mdi:compass-outline
      friendly_name: Direction   
    sensor.pws_wind_mph:
      icon: mdi:speedometer
      friendly_name: Wind Speed 
    sensor.pws_wind_gust_mph:
      icon: mdi:speedometer
      friendly_name: Gust
    sensor.pws_precip_today_in:
      icon: mdi:weather-pouring       
      friendly_name: Rain Today
    sensor.pws_precip_1hr_in:
      icon: mdi:weather-pouring
      friendly_name: Inch Per Hour
    sensor.pws_relative_humidity:
      entity_picture: /local/drop.png   
      friendly_name: Humidity  
    sensor.pws_visibility_mi:
      friendly_name: Visibility
    sensor.dark_sky_daily_summary:
      friendly_name: Daily      
    sensor.dark_sky_hourly_summary:
      friendly_name: Hourly 
    sensor.dark_sky_minutely_summary:
      friendly_name: To the Minute
      
sensor:
  - platform: wunderground
    api_key: !secret wunderground_api
    monitored_conditions:
      - alerts
      - feelslike_f
      - observation_time
      - precip_1hr_in
      - precip_today_in
      - relative_humidity
      - temp_f
      - visibility_mi
      - weather
      - wind_dir
      - wind_gust_mph
      - wind_mph


  - platform: darksky
    api_key: !secret darksky_api
#  forecast:
#  - 1
#  - 2
    monitored_conditions:
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - precip_probability
      - minutely_summary
      - hourly_summary
      - daily_summary
      - temperature_max
      - temperature_min
      - temperature
      - humidity
      - precip_probability
      - precip_intensity
      - wind_speed
      - pressure
      - wind_bearing
      - apparent_temperature
      - icon
      