homeassistant:
  customize:
    automation.fan_set_speed:
      friendly_name: "Fan Set Speed"
      haaska_hidden: true
      hidden: true

    automation.fan_turn_on:
      friendly_name: "Fan Turn On"
      haaska_hidden: true
      hidden: true

    script.living_room_fan_auto:
      friendly_name: "Breeze"
      icon: mdi:fan

    sensor.fan_speed:
      icon: mdi:speedometer
   
    binary_sensor.gang:
      friendly_name: Fan Connection
      icon: mdi:nfc

sensor:
  - platform: template
    sensors:
      fan_speed:
        friendly_name: 'Fan Speed'
        value_template: "{{ states.fan.living_room_fan.attributes.speed }}"

automation:
  - alias: fan_set_speed
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: fan
          service: turn_on
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.service_data.speed is defined }}"
    action:
      - service: automation.turn_off
        data:
          entity_id:
            - automation.fan_set_speed
            - automation.fan_turn_on
      - service: fan.set_speed
        data_template:
          entity_id: "{{ trigger.event.data.service_data.entity_id }}"
          speed: "{{ trigger.event.data.service_data.speed }}"
      - service: fan.turn_on
        data_template:
          entity_id: "{{ trigger.event.data.service_data.entity_id }}"
      - service: automation.turn_on
        data:
          entity_id:
            - automation.fan_set_speed
            - automation.fan_turn_on

  - alias: fan_turn_on
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: call_service
        event_data:
          domain: fan
          service: turn_on
    condition:
      - condition: template
        value_template: "{{ trigger.event.data.service_data.speed is not defined }}"
    action:
      - service: automation.turn_off
        data:
          entity_id:
            - automation.fan_set_speed
            - automation.fan_turn_on
      - service: fan.set_speed
        data_template:
          entity_id: >-
            {% if trigger.event.data.service_data.entity_id is string %}
              {{ trigger.event.data.service_data.entity_id }}
            {% else %}
              {{ trigger.event.data.service_data.entity_id|join(', ') }}
            {% endif %}
          speed: "low"
      - service: fan.turn_on
        data_template:
          entity_id: >-
            {% if trigger.event.data.service_data.entity_id is string %}
              {{ trigger.event.data.service_data.entity_id }}
            {% else %}
              {{ trigger.event.data.service_data.entity_id|join(', ') }}
            {% endif %}
      - service: automation.turn_on
        data:
          entity_id:
            - automation.fan_set_speed
            - automation.fan_turn_on
##########################################################################
############################  cieling fan automation with Hvac    #################
##########################################################################
  - alias: Fan Meduim with Hvac automation
    trigger:
      - platform: state
        entity_id: sensor.hvac_fan
        to: 'on'
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'
    action:
      - service: fan.turn_on
        data:
          entity_id: fan.living_room_fan
          speed: 'medium'
  - alias: Fan low with hvac automation
    trigger:
      - platform: state
        entity_id: sensor.hvac_fan
        to: 'off'
    condition:
      - condition: state
        entity_id: sensor.set_hold_mode
        state: 'home'
    action:
      - service: fan.turn_on
        data:
          entity_id: fan.living_room_fan
          speed: 'low'

  # - alias: turn_the_damn_fan_on
    # trigger:
      # ...
    # action:
      # - service: fan.turn_on
        # data:
          # entity_id: fan.living_room_fan
          # speed: low

script:
  living_room_fan_auto:
    sequence:
      - delay: '00:00:01'
      - service: fan.turn_on
        data:
          entity_id: fan.living_room_fan
          speed: 'auto'
